ch: add app tests
crane-cloud/app-logger pull request #8
Opened 2024-03-21 14:08 UTC by khalifan-kfan

### What this PR does?

Adds initial testing to the application

### How to run it.
 Run ```make test```

<img width="1118" alt="Screenshot 2024-03-21 at 17 06 41" src="https://github.com/crane-cloud/app-logger/assets/69305400/49ce3a6b-a2d4-4008-b75c-c30488a4c27f">

2025-01-22 13:24 UTC, Mubangizi requested changes
Great work, just a few issues to address

2025-01-22 13:24 UTC, Mubangizi commented on Dockerfile
> +ARG FASTAPI_ENV='development'
Remove this, because we use this docker file in staging and prod deployments

2025-01-22 13:24 UTC, Mubangizi commented on docker-compose.yml
> +    external: false
Leave this as true

2025-01-22 13:24 UTC, Mubangizi commented on makefile
> +	@ docker compose -f $(DOCKER_DEV_COMPOSE_FILE) exec app-logger  poetry run pytest --cov=. --cov-report=term-missing
Create the external network at this point

2025-01-22 13:25 UTC, khalifan-kfan commented on Dockerfile
> +ARG FASTAPI_ENV='development'
sure

2025-01-22 13:27 UTC, khalifan-kfan commented on makefile
> +	@ docker compose -f $(DOCKER_DEV_COMPOSE_FILE) exec app-logger  poetry run pytest --cov=. --cov-report=term-missing
nice

2025-01-22 14:34 UTC, khalifan-kfan commented
@Mubangizi  this is done

2025-01-23 09:42 UTC, Mubangizi approved these changes
Great work @khalifan-kfan

2025-01-23 09:43 UTC, merged